### ISSUE TITLE
VScode indentation autofix bug

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#1359]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15635498/93789795-fa8bf380-fc3a-11ea-8bff-512898015e72.gif)

=)

**Comment by sbcgua** [comment]
BZW it is also a bug for indentation rule. Following statements should be ignored imho. There is no way to ignore this issue now but to exclude the whole file ...

**Comment by larshp** [comment]
heh, yea, 

think it should be solved by not reporting it as an issue for the indentation rule

https://rules.abaplint.org/max_one_statement/ should be found first, if its enabled by the user

**Comment by sbcgua** [comment]
max_one_statement is disabled for this file (exclude)

**Comment by larshp** [comment]
@sbcgua try again, 2.49.0 published, indentation is now ignored if there are multiple statements in the same row

**Comment by sbcgua** [comment]
:+1: certainly better, but there is still an issue (maybe another one)
My guess is that the `endmethod` is ignored so much that does not decrement indentation, but i'm not sure

![image](https://user-images.githubusercontent.com/15635498/93882368-ce2eb080-fce8-11ea-8234-c2ed4833081c.png)

![image](https://user-images.githubusercontent.com/15635498/93882323-bf47fe00-fce8-11ea-8592-c0f6b4a4bb9c.png)

**Comment by larshp** [comment]
thanks, always another bug :)

**Comment by larshp** [comment]
@sbcgua try again, 2.49.1 published

**Comment by sbcgua** [comment]
Kind of works ! :) Thanks a lot !

![image](https://user-images.githubusercontent.com/15635498/94000524-f3cac100-fd9f-11ea-8942-29ee6ffd00c5.png)

closing
