### ISSUE TITLE
check_syntax: Constants (defined in include) not found in class

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1868]
Issue:
```
abaplint 2.72.1
Using config: abaplint.json
Clone: https://gitlab+deploy-token-read:vdocker.sap.internal:8929//abap_dependencies/dependencies-core-sap.git
./src/ma/#redwood#cl_ma_aktyp_mapping.clas.abap[30, 13] - c_target_addons not found, findTop (check_syntax) [E]
./src/ma/#redwood#cl_ma_aktyp_mapping.clas.abap[36, 13] - c_target_addons not found, findTop (check_syntax) [E]
./src/ma/#redwood#cl_ma_aktyp_mapping.clas.abap[39, 13] - c_target_addons not found, findTop (check_syntax) [E]
```
The constants are inside an external include. 
I've tried relocating the include (private section, inside the method) but the constants are not found.

Where should the includes be located for linter to find them?

**Comment by larshp** [comment]
heh, I've always thought that INCLUDEs were not allowed in classes. I.e. its not handled in abaplint

![image](https://user-images.githubusercontent.com/5888506/112134078-a0112700-8bcc-11eb-8a10-ad97f2d7627b.png)

**Comment by larshp** [comment]
@ed-holland thanks, can you try reproducing the issue in a public repo?

I've added a testcase, https://github.com/abaplint/abaplint/commit/0eda75094fc6d99588e99e98d07fe9be87d6b917, and it seems to work as expected

**Comment by ed-holland** [comment]
Created a test case with two includes defined in different sections of the class.
https://github.com/ed-holland/AG_Tests.git
Does this work for you?

**Comment by larshp** [comment]
for https://github.com/ed-holland/AG_Tests/pull/1/checks?check_run_id=2244690475 I think it doesnt reproduce the exact issue

but there are false positives with "INCLUDE not used anywhere" which I will fix 😄

**Comment by ed-holland** [comment]
Looks more like the "not-used" is masking the not-found that i currently have with linter.
Additionally to that, i also got this false-positive in another class with include.

![image](https://user-images.githubusercontent.com/53995991/113279067-faa03680-92e2-11eb-8c30-70898a9982b3.png)

On the macro subject. Did you find time the last year to work on that? I had to exclude them from indentation checks.

**Comment by larshp** [comment]
"INCLUDE not used anywhere" fixed, see https://github.com/ed-holland/AG_Tests/pull/1/checks?check_run_id=2245093180

macro: sounds like a false positive, is there a separate issue for it? I think macros should be skipped in the indentation check

**Comment by ed-holland** [comment]
Macros... will create a new issue for that... it is not so easy... just switching it off in macros will create more indent issues.

Will retest my projects when it is merged and available in docker

**Comment by ed-holland** [comment]
I'm still having the issue with the latest AbapLint version. Was the fix not included there?

**Comment by larshp** [comment]
only the "INCLUDE not used anywhere" was fixed, I have not had any luck reproducing the "not found" issue

**Comment by ed-holland** [comment]
Ok, got the following two cases (both BADI implementations). SCI and Lint are almost consistent in their reporting.

Case 1: ext2 is a constant. <accit_tab> is a field-symbol. Both defined in an include. The include also contains macros.
```
./src/ecc/#jcs#cl_fi_badi_acc_document.clas.abap[64, 3] - ext2 not found, findTop (check_syntax) [E]
./src/ecc/#jcs#cl_fi_badi_acc_document.clas.abap[70, 3] - "<accit_tab>" not found, FSTarget (check_syntax) [E]
```

Case 2: Here SCI still has the include not found issue (linter does not have it). All the not founds are constants in the include. There is nothing else in the include.
```
abaplint - -  Line 000000 : Server is OK, abaplint version = 2.73.10
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000003 : Include /REDWOOD/LMAD11 not found (check_include)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000012 : c_target_addons not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000018 : c_target_addons not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000021 : c_target_addons not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000024 : c_target_basics not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000025 : c_basics_status not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000031 : c_target_addons not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000034 : c_target_addons not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000037 : c_target_addons not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000040 : c_target_basics not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000041 : c_basics_status not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000047 : c_target_addons not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000056 : c_target_addons not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000067 : c_info not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000073 : c_info not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000077 : c_target_basics not found, findTop (check_syntax)
abaplint - /REDWOOD/CL_MA_AKTYP_MAPPING  Line 000084 : c_info not found, findTop (check_syntax)
```

I've updated the test-case with a namespace include and a case statement which are both used above.
![image](https://user-images.githubusercontent.com/53995991/114302916-9abc4380-9acb-11eb-9437-b3b3ff7c3970.png)

This now results in the following issues:
![image](https://user-images.githubusercontent.com/53995991/114302933-b0ca0400-9acb-11eb-8a33-ebda5d4071f8.png)

Looks like it is caused by the namespace.

**Comment by larshp** [comment]
Case 1: try removing as much as possible in the include, so we have a minimal example.
Are there any other errors reported for the include?

**Comment by ed-holland** [comment]
Case 1 is using macro inside macro's (local / global).  Will try to reduce it using VC.
Case 2 is in the public repo (if need be i can add the include)

**Comment by ed-holland** [comment]
I've checked the case 1 in VC. 
It is not the namespace in the include (copied it to a z-include and the problem persists).
I've reduced the include to the constant ext2 and the field-symbol <accit_tab>.
Moving them inside the class and all is well.

Original Code (inside extended interface class)
![image](https://user-images.githubusercontent.com/53995991/114987195-2bf93480-9e95-11eb-9dab-8ff092ffff07.png)

**Comment by ed-holland** [comment]
Issue persists with abaplint 2.74.8

**Comment by larshp** [comment]
can the issue be reproduced with https://github.com/ed-holland/AG_Tests/ ?

**Comment by larshp** [comment]
The errors regarding `c_target_addons` are as expected, the constant or variable is not defined anywhere,

![image](https://user-images.githubusercontent.com/5888506/116034027-d118c780-a662-11eb-94f8-455b43c91309.png)

**Comment by ed-holland** [comment]
Closing. Rewrite in #1930
